### ISSUE TITLE
Publish japanese-kit to npm registry

### ISSUE THREAD

**Issue by bucaran** [ashchan/safarikai#10]
I was just about to create my own, but found yours instead!

This plugin would be more developer friendly if it was written in vanilla JavaScript, but I guess some people like their coffee :smile: 

However, it would make contributions easier if you publish `japanese-kit` to the NPM registry in order to be able to `npm install` without the hassle of downloading that other repo directly.

:+1:

**Comment by ashchan** [comment]
Hey @bucaran, just published it as you wish: https://www.npmjs.com/package/japanese-kit

Cheers!
