### ISSUE TITLE
V2.0: Safari App Extension

### ISSUE THREAD

**Issue by ashchan** [ashchan/safarikai#13]
Started making v2.0 as a [Safari App Extension](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/SafariAppExtension_PG/index.html).

If it goes well, the new version will be released on Mac App Store.

It's very likely the dictionary lookup logic will go to native Swift part, and by doing so it might be able to use a more recent copy of EDICT.

Ideally, the EDICT will be a SQLITE3 bundled and queried with native code. This means the injected JavaScript only handles pointing and picking Japanese word, looking up and showing result with the HTML page.

The WIP branch is [app-extension](https://github.com/ashchan/safarikai/tree/app-extension).

**Comment by vebaev** [comment]
Great, will it have ability to inject to Anki the word you looking up?

**Comment by ashchan** [comment]
@vebaev Yet to see that possibility. But at worst, if we want to support that, perhaps we could just offer a 'copy' feature. It's one more step, but won't require too much integration.

For now I need to focus on making it work with EDICT. I hope to have a MVP version early 2017.

**Comment by gingerbeardman** [comment]
What's the status of this new appex version?

**Comment by ashchan** [comment]
@gingerbeardman It's still suspended due to my focus on other projects.

**Comment by ashchan** [comment]
With @apparition47's help and awesome contributions we'll be able to continue this with the old dict. Plan to submit soon with some bugs. When the submission and publish is done, we'll do:

* Fix highlight issues
* Do some research to see if we're able to update the dict file(s)
* Get rid of coffee script and rewrite JS (low priority)

**Comment by ashchan** [comment]
Submitting to App Store. Hopefully we can get this through review. All thanks to @apparition47.
