### ISSUE TITLE
Issue with Facebook messenger text input

### ISSUE THREAD

**Issue by armincerf** [ashchan/safarikai#14]
When typing a message in Japanese in Facebook messenger, if the mouse is moved over some Japanese text (for example a previous message) the message being typed (if still underlined for kanji selection) disappears. A simple fix would be to have the option to blacklist sites from using the extension (If this is already possible please let me know!).

**Comment by ashchan** [comment]
There's no blacklist feature at the moment. The only way to avoid this is disabling safarikai when visiting Facebook.

I'm in the middle of rebuilding this tool (not not anywhere near finish yet). Perhaps would think of a better way to handle this.

**Comment by apparition47** [comment]
Submitted a PR to fix this.
