### ISSUE TITLE
Safarikai throws exception which is unhandled by Office Online apps and causes crash

### ISSUE THREAD

**Issue by olofhellman** [ashchan/safarikai#15]
At line 57 of injected.coffee:

   range = @doc.caretRangeFromPoint @clientX, @clientY

it is possible that caretRangeFromPoint returns null.  The next line  range.startContainer  may then throw an exception which goes unhandled.  Apps like Microsoft's Word Online or PowerPoint Online will not handle these well.

Perhaps a null check is in order?

**Comment by ashchan** [comment]
@olofhellman  Thanks for reporting this bug. Should check null then.

Apple has dropped support for old plugin, and unfortunately I didn't make it out for an upgrade. For now I'm afraid you have to disable Safarikai when visiting sites that have this issue.
