### ISSUE TITLE
Safari no longer supports unsafe extensions.

### ISSUE THREAD

**Issue by OskarPeredo** [ashchan/safarikai#18]
Hello, I'm getting the following error:

“Safarikai” is no longer supported. You can find newer extensions reviewed by Apple in the App Store or Safari Extensions Gallery

I'm using Mojave Public Beta 5, I'm not sure when this extension stopped working, since i just found it recently. Would it be possible to submit it to the app store as an official extension?

**Comment by ashchan** [comment]
Hi @OskarPeredo Yes Apple now requires Safari Extension to be distributed through App Store. Unfortunately that would take quite some effect to modify Safarikai (I tried a few years back but didn't succeed).

To be honest this project is not actively maintained. I don't think I'll make a runnable App Store update any soon.

**Comment by ashchan** [comment]
@apparition47 That's wonderful!

I have no problem at all if you're kind to publish. But to submit it to App Store, you'll have to change a lot of things. Safari extension now requires a host (macOS) app. See the `app-extension` branch I tried 2 years ago without much progress.

If we could make that work, I have my developer account as well so publishing is not the main problem here :-)

**Comment by saxonthebeach** [comment]
> I updated to Safari 12 just today and discovered this issue. I can get this project to run as an unsigned extension with Safari's Extension Builder though (you need to transpile the `.coffee` files before adding the extension).
> 
> ![screen shot 2018-09-18 at 12 21 01](https://user-images.githubusercontent.com/3298414/45662559-5ba8fa00-bb3d-11e8-94ee-109646644fad.png)
> 
> I could try publishing this project on the App Store under my Developer Account if @ashchan allows me to.

Is there somewhere I can go to get a step-by-step-ish guide on how to set it up with extension builder? Not a developer, but decently facile with terminal, etc

**Comment by apparition47** [comment]
@ashchan Looks more involved than I thought. But looks like you've done a lot of the work already. I'll see if I can hack it together if someone doesn't beat me to it.

@saxonthebeach Basically:
```bash
$ npm i -g coffee-script
$ npm i
$ cake build
```
Open the developer tab in Safari > Show Extension Builder > Add new extension > add the `Safarikai.safariextension` folder > Run

**Comment by saxonthebeach** [comment]
Thanks!

**Comment by apparition47** [comment]
@ashchan Which JMdict file were you using? [Trying to build an sqlite3 file](https://github.com/Top-Ranger/jmdict-to-sqlite3) but mine doesn't seem to match the one specified in your SQL query (i.e. no `romaji` or `sense` columns, no `gloss` table).

**Comment by osiyoh** [comment]
Hi guys. I made an account here just to comment. I really hope you find a way to get this on the App Store. I used this extension on a daily basis living Berenice in Japan. I would prefer to keep using Safari on my Apple products instead of Chrome. I tried “furiganify” as a replacement but it’s not even a fraction as useful.

Anyway, just wanted to chime in to say you definitely have fans of this extension.

**Comment by apparition47** [comment]
@ashchan Yes! Please do!

**Comment by tabaquinho** [comment]
I also just came here to say thank you all for trying to do this. I thought I was decent with terminal and stuff, but I couldn't even figure out what should I modify to have it working with extension builder. I updated safari yesterday and I am really mad at this mess, cause I use this for work and my daily stuff (not only living in Japan, also a Japanese student at university haha). So all my cheers for you guys haha :D oh, and if anyone could help me with a very lengthy tutorial on how to get it to work with extension builder, Im in haha

**Comment by ashchan** [comment]
Thanks to @apparition47's great help, v2.0 was submitted to App Store.

Now if it goes through submission review, we can move on to fix the awkward highlighting bug, and possibly update the dict file in the future.

**Comment by saxonthebeach** [comment]
Great work everyone who contributed. Wish I had something to contribute as well. Is there a way to track and/or get notified when the extension is approved?

**Comment by ashchan** [comment]
Guys the app is approved, but not yet appears on app store yet. Let's give it a few hours to show up. The App Store link is:

https://itunes.apple.com/us/app/safarikai/id1437951175?ls=1&mt=12

cc @apparition47 @saxonthebeach @tabaquinho @osiyoh

**Comment by apparition47** [comment]
@ashchan It's live now! When I get time maybe next month, I'll see if we can update the dictionary in it.

**Comment by ashchan** [comment]
@apparition47 Cheers! Now it's working, I'd also spend some time to improve. 👍 💯

**Comment by osiyoh** [comment]
Wow, great job guys! I can't tell you how much this helps me. I wish you all the best in this and future endeavors. 本当にありがとうございます！

**Comment by tommysvr** [comment]
This is great. Well done all.
