### ISSUE TITLE
Disabling Safarikai does not gray out the icon

### ISSUE THREAD

**Issue by beschoenen** [ashchan/safarikai#30]
This behavior has changed since the new app-extension version. In the old version clicking the icon would make it grayer as to indicate it was turned off.

Is it possible to restore this behavior?

**Comment by beschoenen** [comment]
Are there APIs for double-clicking or long-clicking the icon? Cause a long click to enable/disable would be nice as well.

**Comment by ashchan** [comment]
> Are there APIs for double-clicking or long-clicking the icon? Cause a long click to enable/disable would be nice as well.

AFAIK there's no such APIs.

**Comment by ashchan** [comment]
> **Update**: just an idea: when Safarikai is enabled, when we click the icon, it shows the popover from where we can choose to "Enable". When it's disabled, the icon is grayed out, and clicking it enables it directly. It's done by changing the icon image as a true disabled toolbar item won't respond to clicking.

Doesn't seem to work. A toolbar item either triggers a popover or a command. That behavior is decided at design time.

**Comment by ashchan** [comment]
Closing this. Did some research and found ATM a toolbar item with popover cannot change its image on runtime.

**Comment by apparition47** [comment]
I could move the popover settings into the main app then change the toolbar item back to a command to restore the old 1.0 greyed out toolbar icon when enabled/disabled. Wasn't sure what would be best when I originally implemented this at that time.

I'll look into it.

**Comment by ashchan** [comment]
Sounds good to me 👍
