### ISSUE TITLE
Quit the main app when main window is closed

### ISSUE THREAD

**Issue by ashchan** [ashchan/safarikai#42]
Ver 2.3 was binary rejected as there's no way for user to re-open the window. Sigh...

**Comment by apparition47** [comment]
No way to open which window?

**Comment by ashchan** [comment]
Main app. The guide window.

**Comment by apparition47** [comment]
Don't quite understand. Could you show the rejection text?

**Comment by apparition47** [comment]
Is the reason because the main app stays open even when you `⌘W`?

**Comment by ashchan** [comment]
Yes, either: 1, after the user closes the main app's window, she/he can reopen it, or, 2, when the window is closed the app also quits.

I'll go with 2. The main app is not really supposed to be opened anyway :)

**Comment by apparition47** [comment]
I think *2* would work too. Furiganify (another App Extension on the store) also quits when you close the window as well.

**Comment by ashchan** [comment]
Yeah it makes perfect sense 👍
