### ISSUE TITLE
Toggle translation popup via hotkey

### ISSUE THREAD

**Issue by ClarkAllen1556** [ashchan/safarikai#49]
It would be helpful to be able to toggle the translation overlay via a hotkey. When navigating webpages with lots of Japanese text that is placed all over place (ie, Rakuten) the popup can cover other parts of the page. If this already exists I just haven't been able to find how to enable it the settings or documentation.

**Comment by ashchan** [comment]
It looks like a nice to have feature. Would a fixed combination pre-set enough? Or should it allow us to set hotkeys as we wish?

**Comment by rickychien** [comment]
+1 to see this support.

> Would a fixed combination pre-set enough? Or should it allow us to set hotkeys as we wish?

I think it's okay to see a fixed combination pre-set at first (e.g. active mouse hover when holding a `option` key. Then maybe we could enhance this feature to allow user customizing hotkeys in the next step.

**Comment by apparition47** [comment]
Someone more knowledgable could chime in but one possible issue with this is that we might clobber other websites/Mac apps/Safari extensions that use similar keybindings. Another solution is to introduce a 150ms mouseover/hover delay like rikaikun (similar to Safarikai but for Chrome).

**Comment by ashchan** [comment]
Thanks to @apparition47 again for implementing this. 👍

**Comment by rickychien** [comment]
@apparition47 Thanks for adding this feature!

BTW, when hold-to-lookup is enabled, I am still seeing the dictionary popup is appeared. (Usually happened when visiting a new page, switching between browser tabs or OS applications). But the popup will disappear after holding option key.

**Comment by ashchan** [comment]
> @apparition47 Thanks for adding this feature!
> 
> BTW, when hold-to-lookup is enabled, I am still seeing the dictionary popup is appeared. (Usually happened when visiting a new page, switching between browser tabs or OS applications). But the popup will disappear after holding option key.

Yes I noticed that. Could be due to the initial default value from the injected JS file (for every page the injected JS file gets loaded with these default values, then syncs the setting from the extension native code). I still released because I feel this small flaw is acceptable. Thanks for pointing this out.

**Comment by ashchan** [comment]
@rickychien Applied some possible fix: befd951. I'll release later and see if it works.
