### ISSUE TITLE
Breaks drag-drop (in roundcube)

### ISSUE THREAD

**Issue by furkanmustafa** [ashchan/safarikai#5]
Safari 7.0.4, if I enable the plugin, it breaks drag&drop in Roundcube. Might be breaking other apps too, in my case it was Roundcube.

I will also try to investigate what's the problem if I have time.

**Comment by apparition47** [comment]
Submitted a PR to fix this.

**Comment by ashchan** [comment]
Many thanks to @apparition47 for migrating the extension and fix these issues!
