### ISSUE TITLE
Feature request: Option to disable romaji display

### ISSUE THREAD

**Issue by cbothner** [ashchan/safarikai#9]

**Comment by itsDavidFarrell** [comment]
Hi, I tinkered a bit as I also wanted this, and was able to get this to work. All it took was removing the div section for the romaji from the injected.js file

here's a link to the altered file
https://github.com/ashchan/safarikai/commit/12e564569d1e439e3fb007240d76a97c7cd78619

I've rebuilt a version of the .safariextz file with the romaji removed, but not sure how to share it here, or more importantly if that's okay to do or not. Anyway hope this helps.

**Comment by ashchan** [comment]
@itsDavidFarrell If we add this option, it should be one from the extension settings view. That needs a little more work.

The `injected.js` was generated from the coffee script source code. We don't modify this file directly.

Thank you.

**Comment by ashchan** [comment]
The option was added a few months ago but not published. I'm working on a new version which will likely have this option.
